version: '2'
services:
  humipy:
    build: .
    ports:
      - "5000:5000"
    privileged: true
    devices:
      - "/dev/gpiochip0:/dev/gpiochip0"
      - "/dev/gpiochip1:/dev/gpiochip1"
      - "/dev/gpiochip2:/dev/gpiochip2"
      - "/dev/gpiochip3:/dev/gpiochip3"
      - "/dev/gpiochip4:/dev/gpiochip4"
      - "/dev/i2c-1:/dev/i2c-1"
    cap_add:
      - SYS_RAWIO
    restart: always
    labels:
      - "io.balena.local.image=1"
      - "io.balena.local.service=humipy"
  hotspot-service:
    build: ./hotspot
    network_mode: host
    privileged: true
    restart: always
    labels:
      - "io.balena.local.image=1"
      - "io.balena.local.service=hotspot"